### ISSUE TITLE
Support force_delete attribute

### ISSUE THREAD

**Issue by manali14** [infrablocks/terraform-aws-encrypted-bucket#3]
While destroying a bucket, it fails at times since its not empty. Would be great to have support for force_delete option

**Comment by tobyclemson** [comment]
Release [0.1.5](https://registry.terraform.io/modules/infrablocks/encrypted-bucket/aws/1.5.0) supports this option. Pass `allow_destroy_when_objects_present ` as `"yes"`.

Thanks,
Toby
